# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/negfi/Documents/AUT/5th Semester/Digital Design Automation/Project/Phaze1/Smart Parking/Smart Parking.cache/wt} [current_project]
set_property parent.project_path {C:/Users/negfi/Documents/AUT/5th Semester/Digital Design Automation/Project/Phaze1/Smart Parking/Smart Parking.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {{C:/Users/negfi/Documents/AUT/5th Semester/Digital Design Automation/Project/Phaze1/Smart Parking/Smart Parking.srcs/sources_1/new/Smart_Parking.vhd}}
synth_design -top Smart_Parking -part xc7vx485tffg1157-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
write_checkpoint -noxdef Smart_Parking.dcp
catch { report_utilization -file Smart_Parking_utilization_synth.rpt -pb Smart_Parking_utilization_synth.pb }
